DATASET:
  TRAIN: "E:/dataset/license_plate_chars/train.txt"
  VAL: "E:/dataset/license_plate_chars/val.txt"
  NAMES: "configs/coco.names"
MODEL:
  NC: 84
  INPUT_WIDTH: 352
  INPUT_HEIGHT: 352
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: True
  BATCH_SIZE: 64
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
